obj-$(FLOW_NODE_TYPE_TEST) += test.mod

obj-test-$(FLOW_NODE_TYPE_TEST) += \
	blob-validator.o \
	boolean-generator.o \
	boolean-validator.o \
	byte-generator.o \
	byte-validator.o \
	float-generator.o \
	float-validator.o \
	int-generator.o \
	int-validator.o \
	result.o \
	string-validator.o \
	test.o \
	test.json

obj-test-$(FLOW_NODE_TYPE_TEST)-type := flow
