obj-$(FLOW_NODE_TYPE_TEST) += test.mod
obj-test-$(FLOW_NODE_TYPE_TEST) += boolean-generator.o boolean-validator.o
obj-test-$(FLOW_NODE_TYPE_TEST) += int-generator.o int-validator.o
obj-test-$(FLOW_NODE_TYPE_TEST) += result.o test.o test.json float-validator.o
obj-test-$(FLOW_NODE_TYPE_TEST) += float-generator.o blob-validator.o
obj-test-$(FLOW_NODE_TYPE_TEST)-type := flow
