obj-$(FLOW_NODE_TYPE_FLOWER_POWER) += \
	flower-power.mod

obj-flower-power-$(FLOW_NODE_TYPE_FLOWER_POWER) := \
	flower-power.json \
	flower-power.o

headers-$(FLOW_NODE_TYPE_FLOWER_POWER) := \
    include/sol-flower-power.h
