obj-$(FLOW_NODE_TYPE_MAGNETOMETER) += magnetometer.mod
obj-magnetometer-$(FLOW_NODE_TYPE_MAGNETOMETER) := \
	magnetometer.json \
	lsm303.o
obj-magnetometer-$(FLOW_NODE_TYPE_MAGNETOMETER)-type := flow
