obj-$(PIN_MUX_INTEL_GALILEO_REV_D) += intel-galileo-rev-d.mod
obj-intel-galileo-rev-d-$(PIN_MUX_INTEL_GALILEO_REV_D) := intel-galileo-rev-d/intel-galileo-rev-d.o intel-common/intel-common.o
obj-intel-galileo-rev-d-$(PIN_MUX_INTEL_GALILEO_REV_D)-extra-cflags := -I$(top_srcdir)src/modules/pin-mux/intel-common
obj-intel-galileo-rev-d-$(PIN_MUX_INTEL_GALILEO_REV_D)-type := pin-mux

obj-$(PIN_MUX_INTEL_GALILEO_REV_G) += intel-galileo-rev-g.mod
obj-intel-galileo-rev-g-$(PIN_MUX_INTEL_GALILEO_REV_G) := intel-galileo-rev-g/intel-galileo-rev-g.o intel-common/intel-common.o
obj-intel-galileo-rev-g-$(PIN_MUX_INTEL_GALILEO_REV_G)-extra-cflags := -I$(top_srcdir)src/modules/pin-mux/intel-common
obj-intel-galileo-rev-g-$(PIN_MUX_INTEL_GALILEO_REV_G)-type := pin-mux

obj-$(PIN_MUX_INTEL_EDISON_REV_C) += intel-edison-rev-c.mod
obj-intel-edison-rev-c-$(PIN_MUX_INTEL_EDISON_REV_C) := intel-edison-rev-c/intel-edison-rev-c.o intel-common/intel-common.o
obj-intel-edison-rev-c-$(PIN_MUX_INTEL_EDISON_REV_C)-extra-cflags := -I$(top_srcdir)src/modules/pin-mux/intel-common
obj-intel-edison-rev-c-$(PIN_MUX_INTEL_EDISON_REV_C)-type := pin-mux
