obj-$(CONFIG_FLOW_NODE_TYPE_GTK) += gtk.mod
obj-gtk-$(CONFIG_FLOW_NODE_TYPE_GTK) := gtk.json gtk.o byte-editor.o
obj-gtk-$(CONFIG_FLOW_NODE_TYPE_GTK) += label.o led.o pushbutton.o pwm-editor.o
obj-gtk-$(CONFIG_FLOW_NODE_TYPE_GTK) += pwm-viewer.o rgb-editor.o slider.o
obj-gtk-$(CONFIG_FLOW_NODE_TYPE_GTK) += spinbutton.o toggle.o window.o
