sample-$(FLOW_CALAMARI_7SEG_SEGMENTS_SAMPLE) += calamari-7seg-segments
sample-calamari-7seg-segments-$(FLOW_CALAMARI_7SEG_SEGMENTS_SAMPLE) := calamari-7seg-segments.fbp
sample-calamari-7seg-segments-$(FLOW_CALAMARI_7SEG_SEGMENTS_SAMPLE)-conffile := sol-flow-intel-minnow-max-linux_gt_3_17.json

sample-$(FLOW_CALAMARI_7SEG_VALUE_SAMPLE) += calamari-7seg-value
sample-calamari-7seg-value-$(FLOW_CALAMARI_7SEG_VALUE_SAMPLE) := calamari-7seg-value.fbp
sample-calamari-7seg-value-$(FLOW_CALAMARI_7SEG_VALUE_SAMPLE)-conffile := sol-flow-intel-minnow-max-linux_gt_3_17.json

sample-$(FLOW_CALAMARI_BUTTONS_RGB_LED_SAMPLE) += calamari-buttons-rgb-led
sample-calamari-buttons-rgb-led-$(FLOW_CALAMARI_BUTTONS_RGB_LED_SAMPLE) := calamari-buttons-rgb-led.fbp
sample-calamari-buttons-rgb-led-$(FLOW_CALAMARI_BUTTONS_RGB_LED_SAMPLE)-conffile := sol-flow-intel-minnow-max-linux_gt_3_17.json

sample-$(FLOW_CALAMARI_LED_SAMPLE) += calamari-led
sample-calamari-led-$(FLOW_CALAMARI_LED_SAMPLE) := calamari-led.fbp
sample-calamari-led-$(FLOW_CALAMARI_LED_SAMPLE)-conffile := sol-flow-intel-minnow-max-linux_gt_3_17.json

sample-$(FLOW_CALAMARI_LEVER_SAMPLE) += calamari-lever
sample-calamari-lever-$(FLOW_CALAMARI_LEVER_SAMPLE) := calamari-lever.fbp
sample-calamari-lever-$(FLOW_CALAMARI_LEVER_SAMPLE)-conffile := sol-flow-intel-minnow-max-linux_gt_3_17.json

sample-$(FLOW_CALAMARI_RGB_LED_SAMPLE) += calamari-rgb-led
sample-calamari-rgb-led-$(FLOW_CALAMARI_RGB_LED_SAMPLE) := calamari-rgb-led.fbp
sample-calamari-rgb-led-$(FLOW_CALAMARI_RGB_LED_SAMPLE)-conffile := sol-flow-intel-minnow-max-linux_gt_3_17.json

