INCLUDES += \
	-I$(RIOTBASE)/pkg/libsoletta/soletta/build/soletta_sysroot/usr/include/soletta \
	-I$(RIOTBASE)/sys/posix/include \
	-I$(RIOTBASE)/sys/posix/pnet/include \
	-I$(RIOTBASE)/sys/net/include
