test-$(CONFIG_TEST_ARENA) += test-arena
test-test-arena-$(CONFIG_TEST_ARENA) := test.c test-arena.c

test-$(CONFIG_TEST_COAP) += test-coap
test-test-coap-$(CONFIG_TEST_COAP) := test.c test-coap.c

test-$(CONFIG_TEST_FBP) += test-fbp
test-test-fbp-$(CONFIG_TEST_FBP) := test.c test-fbp.c

test-$(CONFIG_TEST_FBP_SCANNER) += test-fbp-scanner
test-test-fbp-scanner-$(CONFIG_TEST_FBP_SCANNER) := test.c test-fbp-scanner.c

test-$(CONFIG_TEST_FLOW) += test-flow
test-test-flow-$(CONFIG_TEST_FLOW) := test.c test-flow.c
test-test-flow-$(CONFIG_TEST_FLOW)-deps := flow-node-type-timer.mod flow-node-type-pwm.mod flow-node-type-console.mod

test-$(CONFIG_TEST_FLOW_BUILDER) += test-flow-builder
test-test-flow-builder-$(CONFIG_TEST_FLOW_BUILDER) := test.c test-flow-builder.c

test-$(CONFIG_TEST_FLOW_PARSER) += test-flow-parser
test-test-flow-parser-$(CONFIG_TEST_FLOW_PARSER) := test.c test-flow-parser.c

test-$(CONFIG_TEST_MAINLOOP) += test-mainloop
test-test-mainloop-$(CONFIG_TEST_MAINLOOP) := test-mainloop.c

test-$(CONFIG_MAINLOOP_LINUX) += test-mainloop-linux
test-test-mainloop-linux-$(CONFIG_MAINLOOP_LINUX) := test-mainloop-linux.c

test-$(CONFIG_TEST_MAINLOOP_THREADS) += test-mainloop-threads
test-test-mainloop-threads-$(CONFIG_TEST_MAINLOOP_THREADS) := test-mainloop-threads.c

test-$(CONFIG_TEST_MAINLOOP_THREADS_SOL_RUN) += test-mainloop-threads-sol-run
test-test-mainloop-threads-sol-run-$(CONFIG_TEST_MAINLOOP_THREADS_SOL_RUN) := test-mainloop-threads-sol-run.c

test-$(CONFIG_TEST_MONITORS) += test-monitors
test-test-monitors-$(CONFIG_TEST_MONITORS) := test.c test-monitors.c

test-$(CONFIG_TEST_STR_SLICE) += test-str-slice
test-test-str-slice-$(CONFIG_TEST_STR_SLICE) := test.c test-str-slice.c

test-$(CONFIG_TEST_STR_TABLE) += test-str-table
test-test-str-table-$(CONFIG_TEST_STR_TABLE) := test.c test-str-table.c

test-$(CONFIG_TEST_VECTOR) += test-vector
test-test-vector-$(CONFIG_TEST_VECTOR) := test.c test-vector.c

test-$(CONFIG_TEST_BUFFER) += test-buffer
test-test-buffer-$(CONFIG_TEST_VECTOR) := test.c test-buffer.c
