obj-$(LINUX_MICRO_AUTOMOUNT) += automount.mod
obj-automount-$(LINUX_MICRO_AUTOMOUNT) += automount.o ../uevent/sol-uevent.o
obj-automount-$(LINUX_MICRO_AUTOMOUNT)-type := linux-micro
obj-automount-$(LINUX_MICRO_AUTOMOUNT)-extra-cflags := -I$(top_srcdir)src/modules/linux-micro/uevent
