sample-$(FLOW_WEBSERVICES_FLOWER_POWER_SAMPLE) += flower-power-http
sample-flower-power-http-$(FLOW_WEBSERVICES_FLOWER_POWER_SAMPLE) := flower-power-http.fbp

sample-$(FLOW_WEBSERVICES_FREEGEO_IP_SAMPLE) += freegeoip
sample-freegeoip-$(FLOW_WEBSERVICES_FREEGEO_IP_SAMPLE) := freegeoip.fbp
