sample-$(FLOW_WEBSERVICES_FLOWER_POWER_SAMPLE) += flower-power-http
sample-flower-power-http-$(FLOW_WEBSERVICES_FLOWER_POWER_SAMPLE) := flower-power-http.fbp

sample-$(FLOW_WEBSERVICES_FREEGEO_IP_SAMPLE) += freegeoip
sample-freegeoip-$(FLOW_WEBSERVICES_FREEGEO_IP_SAMPLE) := freegeoip.fbp

sample-$(FLOW_WEBSERVICES_THINGSPEAK_IDENTIFY_SAMPLE) += thingspeak-identify
sample-thingspeak-identify-$(FLOW_WEBSERVICES_THINGSPEAK_IDENTIFY_SAMPLE) := thingspeak-talkback-identify.fbp

sample-$(FLOW_WEBSERVICES_THINGSPEAK_SMART_LOCK_SAMPLE) += thingspeak-smart-lock
sample-thingspeak-smart-lock-$(FLOW_WEBSERVICES_THINGSPEAK_SMART_LOCK_SAMPLE) := thingspeak-talkback-smart-lock.fbp

sample-$(FLOW_WEBSERVICES_THINGSPEAK_CHANNEL_UPDATE_SAMPLE) += thingspeak-channel-update
sample-thingspeak-channel-update-$(FLOW_WEBSERVICES_THINGSPEAK_CHANNEL_UPDATE_SAMPLE) := thingspeak-channel-update.fbp
