sample-$(FLOW_POWER_SUPPLY_SAMPLE) += \
	battery-capacity \
	power-supplies-list \
	power-supply-info

# capacity

sample-battery-capacity-$(FLOW_POWER_SUPPLY_SAMPLE) := \
	battery-capacity.fbp

sample-battery-capacity-$(FLOW_POWER_SUPPLY_SAMPLE)-deps := \
	flow/power-supply.mod

sample-battery-capacity-$(FLOW_POWER_SUPPLY_SAMPLE)-conffile := \
	sol-flow.json

# list

sample-power-supplies-list-$(FLOW_POWER_SUPPLY_SAMPLE) := \
	power-supplies-list.fbp

sample-power-supply-list-$(FLOW_POWER_SUPPLY_SAMPLE)-deps := \
	flow/power-supply.mod

# info

sample-power-supply-info-$(FLOW_POWER_SUPPLY_SAMPLE) := \
	power-supply-info.fbp

sample-power-supply-info-$(FLOW_POWER_SUPPLY_SAMPLE)-deps := \
	flow/power-supply.mod
