sample-$(FLOW_GROVE_LCD_AUTOSCROLL_SAMPLE) += grove-lcd-autoscroll
sample-grove-lcd-autoscroll-$(FLOW_GROVE_LCD_AUTOSCROLL_SAMPLE) := grove-lcd-autoscroll.fbp
sample-grove-lcd-autoscroll-$(FLOW_GROVE_LCD_AUTOSCROLL_SAMPLE)-conffile := ../sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_LCD_BLINK_SAMPLE) += grove-lcd-blink
sample-grove-lcd-blink-$(FLOW_GROVE_LCD_BLINK_SAMPLE) := grove-lcd-blink.fbp
sample-grove-lcd-blink-$(FLOW_GROVE_LCD_BLINK_SAMPLE)-conffile := ../sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_LCD_CURSOR_SAMPLE) += grove-lcd-cursor
sample-grove-lcd-cursor-$(FLOW_GROVE_LCD_CURSOR_SAMPLE) := grove-lcd-cursor.fbp
sample-grove-lcd-cursor-$(FLOW_GROVE_LCD_CURSOR_SAMPLE)-conffile := ../sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_LCD_DISPLAY_SAMPLE) += grove-lcd-display
sample-grove-lcd-display-$(FLOW_GROVE_LCD_DISPLAY_SAMPLE) := grove-lcd-display.fbp
sample-grove-lcd-display-$(FLOW_GROVE_LCD_DISPLAY_SAMPLE)-conffile := ../sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_LCD_HELLO_WORLD_SAMPLE) += grove-lcd-hello-world
sample-grove-lcd-hello-world-$(FLOW_GROVE_LCD_HELLO_WORLD_SAMPLE) := grove-lcd-hello-world.fbp
sample-grove-lcd-hello-world-$(FLOW_GROVE_LCD_HELLO_WORLD_SAMPLE)-conffile := ../sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_LCD_SCROLL_SAMPLE) += grove-lcd-scroll
sample-grove-lcd-scroll-$(FLOW_GROVE_LCD_SCROLL_SAMPLE) := grove-lcd-scroll.fbp
sample-grove-lcd-scroll-$(FLOW_GROVE_LCD_SCROLL_SAMPLE)-conffile := ../sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_LCD_SET_CURSOR_SAMPLE) += grove-lcd-set-cursor
sample-grove-lcd-set-cursor-$(FLOW_GROVE_LCD_SET_CURSOR_SAMPLE) := grove-lcd-set-cursor.fbp
sample-grove-lcd-set-cursor-$(FLOW_GROVE_LCD_SET_CURSOR_SAMPLE)-conffile := ../sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_LCD_TEXT_DIRECTION_SAMPLE) += grove-lcd-text-direction
sample-grove-lcd-text-direction-$(FLOW_GROVE_LCD_TEXT_DIRECTION_SAMPLE) := grove-lcd-text-direction.fbp
sample-grove-lcd-text-direction-$(FLOW_GROVE_LCD_TEXT_DIRECTION_SAMPLE)-conffile := ../sol-flow-intel-galileo-rev-g.json
