sample-$(MQTT_PUBLISH_SUBSCRIBE_SAMPLES) += mqtt-publish mqtt-subscribe bluemix
sample-mqtt-publish-$(MQTT_PUBLISH_SUBSCRIBE_SAMPLES) := mqtt-publish.c
sample-mqtt-subscribe-$(MQTT_PUBLISH_SUBSCRIBE_SAMPLES) := mqtt-subscribe.c
sample-bluemix-$(MQTT_BLUEMIX_SAMPLE) := bluemix.c
