sample-$(MQTT_PUBLISH_SUBSCRIBE_SAMPLES) += mqtt-publish mqtt-subscribe
sample-mqtt-publish-$(MQTT_PUBLISH_SUBSCRIBE_SAMPLES) := mqtt-publish.c
sample-mqtt-subscribe-$(MQTT_PUBLISH_SUBSCRIBE_SAMPLES) := mqtt-subscribe.c
