sample-$(FLOW_IIO_NETWORK_SAMPLE) += ambient-light-and-proximity-console
sample-ambient-light-and-proximity-console-$(FLOW_IIO_NETWORK_SAMPLE) := ambient-light-and-proximity-console.fbp
sample-ambient-light-and-proximity-console-$(FLOW_IIO_NETWORK_SAMPLE)-conffile := sol-flow-SoFIA-3GR.json

sample-$(FLOW_IIO_NETWORK_SAMPLE) += ambient-light-and-proximity-mqtt
sample-ambient-light-and-proximity-mqtt-$(FLOW_IIO_NETWORK_SAMPLE) := ambient-light-and-proximity-mqtt.fbp
sample-ambient-light-and-proximity-mqtt-$(FLOW_IIO_NETWORK_SAMPLE)-conffile := sol-flow-SoFIA-3GR.json
