sample-$(BLUETOOTH_SAMPLES) += connect-paired heartbeat browse

sample-connect-paired-$(BLUETOOTH_SAMPLES) := connect-paired.c

sample-heartbeat-$(BLUETOOTH_SAMPLES) := heartbeat.c

sample-browse-$(BLUETOOTH_SAMPLES) := browse.c
