sample-$(BLUETOOTH_SAMPLES) += connect-paired heartbeat browse simple-pair

sample-connect-paired-$(BLUETOOTH_SAMPLES) := connect-paired.c

sample-heartbeat-$(BLUETOOTH_SAMPLES) := heartbeat.c

sample-browse-$(BLUETOOTH_SAMPLES) := browse.c

sample-simple-pair-$(BLUETOOTH_SAMPLES) := simple-pair.c
