obj-$(FLOW_NODE_TYPE_PERSISTENCE) += persistence.mod
obj-persistence-$(FLOW_NODE_TYPE_PERSISTENCE) := persistence.json \
	persistence.o \
	fs-storage.o \
	efivarfs-storage.o
obj-persistence-$(FLOW_NODE_TYPE_PERSISTENCE)-type := flow
