sample-$(FLOW_LD_STRIP_LPD8806_SAMPLE) += lpd8806
sample-lpd8806-$(FLOW_LD_STRIP_LPD8806_SAMPLE) := lpd8806.fbp
sample-lpd8806-$(FLOW_LD_STRIP_LPD8806_SAMPLE)-deps := \
	flow/boolean.mod \
	flow/converter.mod \
	flow/int.mod \
	flow/led-strip.mod \
	flow/random.mod \
	flow/timer.mod
