obj-$(PIN_MUX_INTEL_GALILEO_REV_D) += intel-galileo-rev-d.mod
obj-intel-galileo-rev-d-$(PIN_MUX_INTEL_GALILEO_REV_D) := intel-galileo-rev-d.o
obj-intel-galileo-rev-d-$(PIN_MUX_INTEL_GALILEO_REV_D)-type := pin-mux
