obj-$(FLOW_NODE_TYPE_POWER_SUPPLY) += \
	power-supply.mod

obj-power-supply-$(FLOW_NODE_TYPE_POWER_SUPPLY) := \
	power-supply.json \
	power-supply.o

obj-power-supply-$(FLOW_NODE_TYPE_POWER_SUPPLY)-type := flow
