obj-$(CONFIG_FLOW_NODE_TYPE_CALAMARI) += calamari.mod
obj-calamari-$(CONFIG_FLOW_NODE_TYPE_CALAMARI) := calamari.json calamari.o
obj-calamari-$(CONFIG_FLOW_NODE_TYPE_CALAMARI)-deps := flow-node-type-gpio.mod
