sample-$(FLOW_UNIX_SOCKET_SAMPLE) += \
	boolean-reader \
	boolean-writer \
	byte-reader \
	byte-writer \
	direction-vector-reader \
	direction-vector-writer \
	float-reader \
	float-writer \
	int-reader \
	int-writer \
	rgb-reader \
	rgb-writer \
	string-reader \
	string-writer

sample-boolean-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	boolean-reader.fbp
sample-boolean-reader-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/console.mod \
	flow/unix-socket.mod

sample-boolean-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	boolean-writer.fbp
sample-boolean-writer-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/keyboard.mod \
	flow/unix-socket.mod

sample-byte-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	byte-reader.fbp
sample-byte-reader-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/console.mod \
	flow/unix-socket.mod

sample-byte-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	byte-writer.fbp
sample-byte-writer-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/converter.mod \
	flow/int.mod \
	flow/keyboard.mod \
	flow/timer.mod \
	flow/unix-socket.mod

sample-direction-vector-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	direction-vector-reader.fbp
sample-direction-vector-reader-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/console.mod \
	flow/unix-socket.mod

sample-direction-vector-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	direction-vector-writer.fbp
sample-direction-vector-writer-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/constant.mod \
	flow/converter.mod \
	flow/int.mod \
	flow/keyboard.mod \
	flow/timer.mod \
	flow/unix-socket.mod

sample-float-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	float-reader.fbp
sample-float-reader-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/console.mod \
	flow/unix-socket.mod

sample-float-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	float-writer.fbp
sample-float-writer-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/converter.mod \
	flow/int.mod \
	flow/keyboard.mod \
	flow/timer.mod \
	flow/unix-socket.mod

sample-int-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	int-reader.fbp
sample-int-reader-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/console.mod \
	flow/keyboard.mod \
	flow/unix-socket.mod

sample-int-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	int-writer.fbp
sample-int-writer-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/int.mod \
	flow/keyboard.mod \
	flow/timer.mod \
	flow/unix-socket.mod

sample-rgb-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	rgb-reader.fbp
sample-rgb-reader-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/console.mod \
	flow/unix-socket.mod

sample-rgb-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	rgb-writer.fbp
sample-rgb-writer-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/constant.mod \
	flow/converter.mod \
	flow/int.mod \
	flow/keyboard.mod \
	flow/timer.mod \
	flow/unix-socket.mod

sample-string-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	string-reader.fbp
sample-string-reader-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/console.mod \
	flow/unix-socket.mod

sample-string-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	string-writer.fbp
sample-string-writer-$(FLOW_UNIX_SOCKET_SAMPLE)-deps := \
	flow/converter.mod \
	flow/int.mod \
	flow/keyboard.mod \
	flow/timer.mod \
	flow/unix-socket.mod
