sample-$(FLOW_UNIX_SOCKET_SAMPLE) += \
	boolean-reader \
	boolean-writer \
	byte-reader \
	byte-writer \
	direction-vector-reader \
	direction-vector-writer \
	float-reader \
	float-writer \
	int-reader \
	int-writer \
	rgb-reader \
	rgb-writer \
	string-reader \
	string-writer

sample-boolean-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	boolean-reader.fbp

sample-boolean-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	boolean-writer.fbp

sample-byte-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	byte-reader.fbp

sample-byte-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	byte-writer.fbp

sample-direction-vector-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	direction-vector-reader.fbp

sample-direction-vector-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	direction-vector-writer.fbp

sample-float-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	float-reader.fbp

sample-float-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	float-writer.fbp

sample-int-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	int-reader.fbp

sample-int-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	int-writer.fbp

sample-rgb-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	rgb-reader.fbp

sample-rgb-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	rgb-writer.fbp

sample-string-reader-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	string-reader.fbp

sample-string-writer-$(FLOW_UNIX_SOCKET_SAMPLE) := \
	string-writer.fbp
