sample-$(FLOW_SEMAPHORE_MONITOR_SEMAPHORE_MONITOR_CONSOLE_SAMPLE) += semaphore-monitor-console
sample-semaphore-monitor-console-$(FLOW_SEMAPHORE_MONITOR_SEMAPHORE_MONITOR_CONSOLE_SAMPLE) := semaphore-monitor-console.fbp
sample-semaphore-monitor-console-$(FLOW_SEMAPHORE_MONITOR_SEMAPHORE_MONITOR_CONSOLE_SAMPLE)-deps := \
	flow/console.mod \
	flow/constant.mod \
	flow/http-client.mod \
	flow/string.mod \
	flow/timer.mod
