obj-$(FLOW_NODE_TYPE_FILTER_REPEATED) += filter-repeated.mod
obj-filter-repeated-$(FLOW_NODE_TYPE_AIO) := filter-repeated.json filter-repeated.o
obj-filter-repeated-$(FLOW_NODE_TYPE_AIO)-type := flow
