obj-$(DATATYPES) += datatypes.mod

obj-datatypes-$(DATATYPES) := \
    sol-arena.o \
    sol-buffer.o \
    sol-str-slice.o \
    sol-str-table.o\
    sol-vector.o

headers-y := \
    include/sol-arena.h \
    include/sol-list.h \
    include/sol-str-table.h \
    include/sol-buffer.h \
    include/sol-str-slice.h \
    include/sol-vector.h
