sample-$(FLOW_HTTP_CLIENT_SAMPLE) += \
	client-generic \
	request

sample-client-generic-$(FLOW_HTTP_CLIENT_SAMPLE) := \
	http-client-generic.fbp

sample-request-$(FLOW_HTTP_CLIENT_SAMPLE) := \
	http-request.fbp
