#!/bin/bash

# This file is part of the Soletta Project
#
# Copyright (C) 2015 Intel Corporation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#   * Neither the name of Intel Corporation nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

COMPILE_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
SOLETTA_TARGET=$COMPILE_DIR/opt/solda-intel-galileo-gen2-soletta-master/sysroot/
source $COMPILE_DIR/common-compile.sh
# Don't forget to set PATH_TO_SDK. This script is worth looking into. Maybe
# it should be changed a bit in order to correct a few paths.
source $COMPILE_DIR/opt/solda-intel-galileo-gen2-soletta-master/env.sh

mkdir -p $COMPILE_DIR/initramfs/dev
# SOL_CC is defined  in env.sh. This command will compile the soletta app
SOL_CC -o $COMPILE_DIR/initramfs/init $(find -name '*.c')
if [ $? -ne 0 ]; then
    exit 1
fi

pushd .

cd $COMPILE_DIR/initramfs/dev
sudo mknod -m 622 console c 5 1
sudo mknod -m 622 tty0 c 4 0

cd $COMPILE_DIR/initramfs
find . | cpio -H newc -o > $COMPILE_DIR/initramfs.cpio

cd $COMPILE_DIR
cat initramfs.cpio | gzip > initramfs.cpio.gz

sudo mount -o loop,offset=1048576 base.img /mnt
sudo cp initramfs.cpio.gz /mnt
sudo umount /mnt

popd
mkdir $PLATFORM_NAME
cp $COMPILE_DIR/base.img $PLATFORM_NAME/flash.img
cp $COMPILE_DIR/flash.sh $PLATFORM_NAME
zip -r output.zip $PLATFORM_NAME
