sample-$(FLOW_TRASH_DISPOSER) += trash-disposer
sample-trash-disposer-$(FLOW_TRASH_DISPOSER) := trash-disposer.fbp
sample-trash-disposer-$(FLOW_TRASH_DISPOSER)-conffile := contiki-config.json
sample-trash-disposer-$(FLOW_TRASH_DISPOSER)-deps := \
	flow/boolean.mod \
	flow/console.mod \
	flow/constant.mod \
	flow/converter.mod \
	flow/gpio.mod \
	flow/servo-motor.mod \
	flow/timer.mod
