sample-$(FLOW_TRASH_DISPOSER) += trash-disposer
sample-trash-disposer-$(FLOW_TRASH_DISPOSER) := trash-disposer.fbp
sample-trash-disposer-$(FLOW_TRASH_DISPOSER)-conffile := contiki-config.json
sample-trash-disposer-$(FLOW_TRASH_DISPOSER)-deps := flow/servo-motor.mod flow/gpio.mod
