sample-$(FLOW_COMPASS_LSM303_SAMPLE) += compass-lsm303
sample-compass-lsm303-$(FLOW_COMPASS_LSM303_SAMPLE) := lsm303.fbp
sample-compass-lsm303-$(FLOW_COMPASS_LSM303_SAMPLE)-deps := \
	flow/accelerometer.mod \
	flow/compass.mod
