sample-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE) += cmdline-args
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE) := cmdline-args.fbp
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE)-deps := flow/boolean.mod flow/app.mod flow/console.mod
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE)-deps += flow/int.mod flow/constant.mod
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE)-deps += flow/converter.mod

sample-$(FLOW_BASICS_FIBONACCI_SAMPLE) += fibonacci
sample-fibonacci-$(FLOW_BASICS_FIBONACCI_SAMPLE) := fibonacci.fbp
sample-fibonacci-$(FLOW_BASICS_FIBONACCI_SAMPLE)-deps := \
	flow/app.mod \
	flow/boolean.mod \
	flow/console.mod \
	flow/constant.mod \
	flow/converter.mod \
	flow/int.mod \
	flow/switcher.mod

sample-$(FLOW_BASICS_PLATORM_SERVICE_SAMPLE) += platform-service
sample-platform-service-$(FLOW_BASICS_PLATORM_SERVICE_SAMPLE) := platform-service.fbp
sample-platform-service-$(FLOW_BASICS_PLATORM_SERVICE_SAMPLE)-deps := \
	flow/console.mod \
	flow/platform.mod \
	flow/timer.mod

sample-$(FLOW_BASICS_SIMPLE_SAMPLE) += simple-fbp
sample-simple-fbp-$(FLOW_BASICS_SIMPLE_SAMPLE) := simple.fbp
sample-simple-fbp-$(FLOW_BASICS_SIMPLE_SAMPLE)-deps := flow/timer.mod flow/boolean.mod flow/console.mod

sample-$(FLOW_BASICS_SUBPROCESS_BC_SAMPLE) += subprocess-bc
sample-subprocess-bc-$(FLOW_BASICS_SUBPROCESS_BC_SAMPLE) := subprocess_bc.fbp
sample-subprocess-bc-$(FLOW_BASICS_SUBPROCESS_BC_SAMPLE)-deps := \
	flow/console.mod \
	flow/constant.mod \
	flow/process.mod
