sample-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE) += cmdline-args
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE) := cmdline-args.fbp
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE)-deps := boolean.mod app.mod console.mod 
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE)-deps += int.mod constant.mod
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE)-deps += converter.mod

sample-$(FLOW_BASICS_FIBONACCI_SAMPLE) += fibonacci
sample-fibonacci-$(FLOW_BASICS_FIBONACCI_SAMPLE) := fibonacci.fbp
sample-fibonacci-$(FLOW_BASICS_FIBONACCI_SAMPLE)-deps := int.mod

sample-$(FLOW_BASICS_PLATORM_SERVICE_SAMPLE) += platform-service
sample-platform-service-$(FLOW_BASICS_PLATORM_SERVICE_SAMPLE) := platform-service.fbp

sample-$(FLOW_BASICS_SIMPLE_SAMPLE) += simple-fbp
sample-simple-fbp-$(FLOW_BASICS_SIMPLE_SAMPLE) := simple.fbp
sample-simple-fbp-$(FLOW_BASICS_SIMPLE_SAMPLE)-deps := timer.mod boolean.mod console.mod

sample-$(FLOW_BASICS_SUBPROCESS_BC_SAMPLE) += subprocess-bc
sample-subprocess-bc-$(FLOW_BASICS_SUBPROCESS_BC_SAMPLE) := subprocess_bc.fbp
sample-subprocess-bc-$(FLOW_BASICS_SUBPROCESS_BC_SAMPLE)-deps := process.mod
