obj-$(PIN_MUX_INTEL_EDISON_REV_C) += intel-edison-rev-c.mod
obj-intel-edison-rev-c-$(PIN_MUX_INTEL_EDISON_REV_C) := intel-edison-rev-c.o
obj-intel-edison-rev-c-$(PIN_MUX_INTEL_EDISON_REV_C)-type := pin-mux
