obj-$(FLOW_METATYPE_HTTP_COMPOSED_SERVER) += http-composed-server.mod

obj-http-composed-server-$(FLOW_METATYPE_HTTP_COMPOSED_SERVER) += \
	http-composed-server.o
obj-http-composed-server-$(FLOW_METATYPE_HTTP_COMPOSED_SERVER)-type := flow-metatype
