sample-$(NETWORK_SAMPLES) += network-status
sample-network-status-$(NETWORK_STATUS_SAMPLE) := network-status.c

sample-$(ECHO_SERVER_SAMPLE) += echo-server
sample-echo-server-$(ECHO_SERVER_SAMPLE) := echo-server.c

sample-$(ECHO_CLIENT_SAMPLE) += echo-client
sample-echo-client-$(ECHO_CLIENT_SAMPLE) := echo-client.c

sample-$(NETCTL) += netctl
sample-netctl-$(NETCTL) := netctl.c
sample-netctl-$(NETCTL)-deps := lib/comms/sol-netctl-impl-connman.o

