sample-$(NETWORK_SAMPLES) += network-status
sample-network-status-$(NETWORK_STATUS_SAMPLE) := network-status.c

sample-$(ECHO_SERVER_SAMPLE) += echo-server
sample-echo-server-$(ECHO_SERVER_SAMPLE) := echo-server.c
