sample-$(LINUX_MICRO_INIT_SAMPLE) += linux-micro-init
sample-linux-micro-init-$(LINUX_MICRO_INIT_SAMPLE) := linux-micro-init.c

sample-$(PLATFORM_SIMPLE_SAMPLE) += platform-simple
sample-platform-simple-$(PLATFORM_SIMPLE_SAMPLE) := platform-simple.c

sample-$(UART_SAMPLE) += uart-sample
sample-uart-sample-$(UART_SAMPLE) := uart.c
