sample-$(FLOW_OIC_AND_HTTP_LIGHT_SAMPLE) += \
	oic-and-http-light-server
#	http-controller \
#	oic-controller \

sample-oic-and-http-light-server-$(FLOW_OIC_AND_HTTP_LIGHT_SAMPLE) := \
	oic-and-http-light-server.fbp
sample-oic-and-http-light-server-$(FLOW_OIC_AND_HTTP_LIGHT_SAMPLE)-conffile := \
	sol-flow.json

# TODO: these 2 are broken due problems with sol-fbp-generator
# sample-http-controller-$(FLOW_OIC_AND_HTTP_LIGHT_SAMPLE) := \
# 	http-controller.fbp
# sample-http-controller-$(FLOW_OIC_AND_HTTP_LIGHT_SAMPLE)-conffile := \
# 	sol-flow.json
#
# sample-oic-controller-$(FLOW_OIC_AND_OIC_LIGHT_SAMPLE) := \
# 	oic-controller.fbp
# sample-oic-controller-$(FLOW_OIC_AND_OIC_LIGHT_SAMPLE)-conffile := \
# 	sol-flow.json
