sample-$(COAP_SAMPLES) += coap-sample-client coap-sample-server
sample-coap-sample-client-$(COAP_SAMPLES) := simple-client.c
sample-coap-sample-server-$(COAP_SAMPLES) := simple-server.c

sample-$(OIC_SAMPLES) += oic-sample-client oic-sample-server
sample-oic-sample-client-$(OIC_SAMPLES) := oic-client.c
sample-oic-sample-server-$(OIC_SAMPLES) := oic-server.c
