sample-$(DOWNLOAD_SAMPLE) += download static-files server
sample-download-$(DOWNLOAD_SAMPLE) := download.c
sample-static-files-$(STATIC_FILES_SAMPLE) := static-files.c
sample-server-$(SERVER_SAMPLE) := server.c

