sample-$(FLOW_OIC_SAMPLE) += \
	light-client \
	light-server

sample-light-client-$(FLOW_OIC_SAMPLE) := \
	light-client.fbp
sample-light-client-$(FLOW_OIC_SAMPLE)-conffile := \
	light-client.json

sample-light-server-$(FLOW_OIC_SAMPLE) := \
	light-server.fbp
