sample-$(FLOW_OIC_SAMPLE) += \
	light-client \
	light-server

sample-light-client-$(FLOW_OIC_SAMPLE) := \
	light-client.fbp
sample-light-client-$(FLOW_OIC_SAMPLE)-deps := \
	flow/boolean.mod \
	flow/timer.mod \
	oic.mod
sample-light-client-$(FLOW_OIC_SAMPLE)-conffile := \
	light-client.json

sample-light-server-$(FLOW_OIC_SAMPLE) := \
	light-server.fbp
sample-light-server-$(FLOW_OIC_SAMPLE)-deps := \
	oic.mod \
	flow/console.mod
sample-light-server-$(FLOW_OIC_SAMPLE)-conffile := \
	light-server.json
