sample-$(FLOW_OIC_SCAN_SAMPLE) += \
	light-client-scan-gtk

sample-light-client-scan-gtk-$(FLOW_OIC_SCAN_SAMPLE) := \
	light-client-scan.fbp
sample-light-client-scan-gtk-$(FLOW_OIC_SCAN_SAMPLE)-conffile := \
	sol-flow.json
