obj-$(FLOW_METATYPE_HTTP_COMPOSED_CLIENT) += http-composed-client.mod

obj-http-composed-client-$(FLOW_METATYPE_HTTP_COMPOSED_CLIENT) += \
	http-composed-client.o
obj-http-composed-client-$(FLOW_METATYPE_HTTP_COMPOSED_CLIENT)-type := flow-metatype
