sample-$(FLOW_HTTP_JSON_SAMPLE) += \
	openweathermap \
	temboo_weather \
	temperature_display \
	weather_from_location \
	yahoo_weather

sample-openweathermap-$(FLOW_HTTP_JSON_SAMPLE) := \
	openweathermap.fbp

sample-temboo_weather-$(FLOW_HTTP_JSON_SAMPLE) := \
	temboo_weather.fbp

sample-temperature_display-$(FLOW_HTTP_JSON_SAMPLE) := \
	temperature_display.fbp

sample-weather_from_location-$(FLOW_HTTP_JSON_SAMPLE) := \
	weather_from_location.fbp

sample-yahoo_weather-$(FLOW_HTTP_JSON_SAMPLE) := \
	yahoo_weather.fbp
