sample-$(FLOW_TELEGRAM_JS_SAMPLE) += telegram
sample-telegram-$(FLOW_TELEGRAM_JS_SAMPLE) := telegram.fbp

sample-telegram-$(FLOW_TELEGRAM_JS_SAMPLE)-deps := flow-metatype/js.mod

sample-telegram-$(FLOW_TELEGRAM_JS_SAMPLE)-extra += $(top_srcdir)src/thirdparty/duktape/src/duktape.c
sample-telegram-$(FLOW_TELEGRAM_JS_SAMPLE)-cflags += -I$(top_srcdir)src/thirdparty/duktape/src/ -Wno-float-equal \
	-Wno-format-nonliteral -Wno-suggest-attribute=noreturn

sample-$(FLOW_MY_COUNTER_JS_SAMPLE) += mycounter
sample-mycounter-$(FLOW_MY_COUNTER_JS_SAMPLE) := mycounter.fbp
sample-mycounter-$(FLOW_MY_COUNTER_JS_SAMPLE)-deps := flow-metatype/js.mod

sample-mycounter-$(FLOW_MY_COUNTER_JS_SAMPLE)-extra += $(top_srcdir)src/thirdparty/duktape/src/duktape.c
sample-mycounter-$(FLOW_MY_COUNTER_JS_SAMPLE)-cflags += -I$(top_srcdir)src/thirdparty/duktape/src/ -Wno-float-equal \
	-Wno-format-nonliteral -Wno-suggest-attribute=noreturn

sample-$(FLOW_ATTENDEE_JS_SAMPLE) += attendee
sample-attendee-$(FLOW_ATTENDEE_JS_SAMPLE) := attendee.fbp
sample-attendee-$(FLOW_ATTENDEE_JS_SAMPLE)-deps := flow-metatype/js.mod

sample-attendee-$(FLOW_ATTENDEE_JS_SAMPLE)-extra += $(top_srcdir)src/thirdparty/duktape/src/duktape.c
sample-attendee-$(FLOW_ATTENDEE_JS_SAMPLE)-cflags += -I$(top_srcdir)src/thirdparty/duktape/src/ -Wno-float-equal \
	-Wno-format-nonliteral -Wno-suggest-attribute=noreturn
