obj-$(FLOW_NODE_TYPE_ROBOTICS) += robotics.mod
obj-robotics-$(FLOW_NODE_TYPE_ROBOTICS) := robotics.json robotics.o
obj-robotics-$(FLOW_NODE_TYPE_ROBOTICS)-type := flow
obj-robotics-$(FLOW_NODE_TYPE_ROBOTICS)-extra-ldflags = -lm
