obj-$(FLOW_NODE_TYPE_TRIGONOMETRY) += trigonometry.mod
obj-trigonometry-$(FLOW_NODE_TYPE_TRIGONOMETRY) := trigonometry.json trigonometry.o
obj-trigonometry-$(FLOW_NODE_TYPE_TRIGONOMETRY)-type := flow
