sample-$(FLOW_NETCTL_SAMPLE) += \
	list-network-services \
	network-connect \
	network-disconnect

# list

sample-list-network-services-$(FLOW_NETCTL_SAMPLE) := \
	list-network-services.fbp

sample-list-network-services-$(FLOW_NETCTL_SAMPLE)-deps := \
	flow/netctl.mod

#connection

sample-network-connect-$(FLOW_NETCTL_SAMPLE) := \
	network-connect.fbp

sample-network-disconnect-$(FLOW_NETCTL_SAMPLE) := \
	network-disconnect.fbp

sample-network-connection-$(FLOW_NETCTL_SAMPLE)-deps := \
	flow/netctl.mod


