sample-$(FLOW_NETCTL_SAMPLE) += \
	list-network-services \
	network-connect \
	network-disconnect \
	network-radios

sample-$(FLOW_NETCTL_SAMPLE)-deps := \
	flow/netctl.mod
# list

sample-list-network-services-$(FLOW_NETCTL_SAMPLE) := \
	list-network-services.fbp

#connection

sample-network-connect-$(FLOW_NETCTL_SAMPLE) := \
	network-connect.fbp

sample-network-disconnect-$(FLOW_NETCTL_SAMPLE) := \
	network-disconnect.fbp

#radios

sample-network-radios-$(FLOW_NETCTL_SAMPLE) := \
	network-radios.fbp
