/* this file was auto-generated by Soletta's template.py script */

#pragma once

{{
import os

def gen_builtins(decl, item, array, count, builtins):
    builtins = os.environ.get(builtins)
    builtins = builtins.strip()
    if builtins:
        builtins = builtins.replace("-","_").split(" ")

    decl = decl.replace("@NAME@", "%(NAME)s").replace("@name@", "%(name)s")
    item = item.replace("@NAME@", "%(NAME)s").replace("@name@", "%(name)s")
    for b in builtins:
        vrs = {
            "name": b.lower(),
            "NAME": b.upper()
        }
        st.println("extern %s;" % (decl % vrs))
    if builtins:
        st.println("%s = {" % array)
        for b in builtins:
            vrs = {
                "name": b.lower(),
                "NAME": b.upper()
            }
            st.println("    %s," % (item % vrs))
        st.println("};")
    st.println("#define %s %d" % (count, len(builtins)))
}}
