sample-$(FLOW_IIO_SAMPLE) += iio-gyro
sample-iio-gyro-$(FLOW_IIO_SAMPLE) := gyroscope.fbp
sample-iio-gyro-$(FLOW_IIO_SAMPLE)-conffile := sol-flow-intel-minnow-max-linux_gt_3_17.json

sample-$(FLOW_IIO_SAMPLE) += iio-magnet
sample-iio-magnet-$(FLOW_IIO_SAMPLE) := magnet.fbp
sample-iio-magnet-$(FLOW_IIO_SAMPLE)-conffile := sol-flow-intel-minnow-max-linux_gt_3_17.json
