sample-$(FLOW_BASICS_SIMPLE_SAMPLE) += simple-fbp
sample-simple-fbp-$(FLOW_BASICS_SIMPLE_SAMPLE) := basics/simple.fbp
sample-simple-fbp-$(FLOW_BASICS_SIMPLE_SAMPLE)-deps := timer.mod boolean.mod console.mod

sample-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE) += cmdline-args
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE) := basics/cmdline-args.fbp
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE)-deps := boolean.mod app.mod console.mod int.mod constant.mod
sample-cmdline-args-$(FLOW_BASICS_CMDLINE_ARGS_SAMPLE)-deps += converter.mod

sample-$(FLOW_BASICS_FIBONACCI_SAMPLE) += fibonacci
sample-fibonacci-$(FLOW_BASICS_FIBONACCI_SAMPLE) := basics/fibonacci.fbp
sample-fibonacci-$(FLOW_BASICS_FIBONACCI_SAMPLE)-deps := int.mod

sample-$(FLOW_BASICS_PLATORM_SERVICE_SAMPLE) += platform-service
sample-platform-service-$(FLOW_BASICS_PLATORM_SERVICE_SAMPLE) := basics/platform-service.fbp

sample-$(FLOW_COMPASS_LSM303_SAMPLE) += compass-lsm303
sample-compass-lsm303-$(FLOW_COMPASS_LSM303_SAMPLE) := compass/lsm303.fbp
sample-compass-lsm303-$(FLOW_COMPASS_LSM303_SAMPLE)-deps := accelerometer.mod magnetometer.mod

sample-$(FLOW_FOOSBAL_SAMPLE) += foosball
sample-foosball-$(FLOW_FOOSBALL_SAMPLE) := foosball/foosball.fbp foosball/tracker.fbp

sample-$(FLOW_GTK_GALLERY_SAMPLE) += gtk-sample
sample-gtk-sample-$(FLOW_GTK_GALLERY_SAMPLE) := gtk-gallery/gtk-gallery.fbp
sample-gtk-sample-$(FLOW_GTK_GALLERY_SAMPLE)-deps := gtk.mod

sample-$(FLOW_LD_STRIP_LDP8806_SAMPLE) += ldp8806
sample-ldp8806-$(FLOW_LD_STRIP_LDP8806_SAMPLE) := ld-strip/ldp8806.fbp

sample-$(FLOW_MISC_FILE_COPY_SAMPLE) += file-copy
sample-file-copy-$(FLOW_MISC_FILE_COPY_SAMPLE) := misc/file-copy.fbp
sample-file-copy-$(FLOW_MISC_FILE_COPY_SAMPLE)-deps := file.mod
