sample-$(FLOW_BASIC_SAMPLE) += simple-fbp
sample-simple-fbp-$(FLOW_BASIC_SAMPLE) := basics/simple.fbp
sample-simple-fbp-$(FLOW_BASIC_SAMPLE)-deps := timer.mod boolean.mod console.mod

sample-$(FLOW_CMDLINE_ARGS_SAMPLE) += cmdline-args
sample-cmdline-args-$(FLOW_CMDLINE_ARGS_SAMPLE) := basics/cmdline-args.fbp
sample-cmdline-args-$(FLOW_CMDLINE_ARGS_SAMPLE)-deps := boolean.mod app.mod console.mod int.mod constant.mod
sample-cmdline-args-$(FLOW_CMDLINE_ARGS_SAMPLE)-deps += converter.mod
