sample-$(FLOW_FOOSBALL_SAMPLE) += foosball
sample-foosball-$(FLOW_FOOSBALL_SAMPLE) := \
	foosball.fbp
sample-foosball-$(FLOW_FOOSBALL_SAMPLE)-deps := \
	flow/boolean.mod \
	flow/constant.mod \
	flow/converter.mod \
	flow/int.mod \
	flow/timer.mod \
	gtk.mod \
	tracker.fbp
