sample-$(IIO_MQTT_SAMPLES) += iio-gyroscope-console-and-mqtt-publish iio-magnetometer-console-and-mqtt-publish
sample-iio-gyroscope-console-and-mqtt-publish-$(IIO_MQTT_SAMPLES) := iio-gyroscope-console-and-mqtt-publish.c
sample-iio-magnetometer-console-and-mqtt-publish-$(IIO_MQTT_SAMPLES) := iio-magnetometer-console-and-mqtt-publish.c matrix-ops.c
sample-iio-magnetometer-console-and-mqtt-publish-$(IIO_MQTT_SAMPLES)-extra-ldflags = -lm
