#!/bin/bash

# This file is part of the Soletta™ Project
#
# Copyright (C) 2015 Intel Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

function die() {
    echo "ERROR: $1"
    exit 1
}

[ -e ./Kconfig ] || die "Call from the root directory."

usage() {
    echo "
Usage: $(basename $0) [OPTIONS]
Show size of the library compiled in different configurations

OPTIONS
    -a             show size of all modules in addition to the library
    -l             do not disable log from the build
    -h             display this help message
" 1>&2;
    exit 1;
}

OPT_ALL=0
OPT_KEEP_LOG=0
args=
for arg in "$@"; do
    case "$arg" in
        -a) OPT_ALL=1
            ;;
        -l) OPT_KEEP_LOG=1
            ;;
        -h) usage
            ;;
        *) args="$args $arg"
            ;;
    esac
done
IFS=' ' read -a args <<< "$args"

if [ $OPT_KEEP_LOG -eq 0 ]; then
    echo "# logs disabled"
else
    echo "# logs enabled"
fi

echo

function calc_size() {
    echo "# building with CFLAGS='$@'"
    make clean > /dev/null
    make alldefconfig > /dev/null
    if [ $OPT_KEEP_LOG -eq 0 ]; then
	sed -i "s/^LOG=y/LOG=n/" .config
    fi
    make CFLAGS="$@" -j4 &> /dev/null || die "Error compiling with $@"
    LIB=*
    if [ $OPT_ALL -eq 0 ]; then
	LIB=libsoletta
    fi
    find -name "$LIB.so" -exec size '{}' +
    echo
}

calc_size -Os
calc_size -O2
