#!/bin/bash

# This file is part of the Soletta Project
#
# Copyright (C) 2015 Intel Corporation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#   * Neither the name of Intel Corporation nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Generate SVG representations of all FBP files in the repository.
# ./generate-svg-from-all-fbps path/to/sol-fbp-to-dot path/to/output_dir

set -euo pipefail

# Default paths
OUTPUT=$PWD/doc/node-types-html/svg
FBP_TO_DOT=$PWD/build/soletta_sysroot/usr/bin/sol-fbp-to-dot

THUMB_SIZE=89

if [[ ! -z "$1" ]]; then
    FBP_TO_DOT=$1
fi

if [[ ! -z "$2" ]]; then
    OUTPUT=$2
fi

function die() {
    echo "ERROR: $1"
    exit 1
}

[ -e ./Kconfig ] || die "Call from the root directory."
[ -e $FBP_TO_DOT ] || die "Couldn't find sol-fbp-to-dot."

for f in $(find src/ -name \*.fbp); do
    # skip error tests
    if grep "TEST-EXPECTS-ERROR" ${f} > /dev/null; then
       continue
    fi

    dir=$(dirname $f)
    mkdir -p $OUTPUT/$dir

    f_dot=$OUTPUT/${f/.fbp/.dot}
    f_svg=$OUTPUT/${f/.fbp/.svg}
    f_thumb=$OUTPUT/${f/.fbp/_thumb.jpg}

    # Copy fbp used to generate svg removing license.
    # It's going to be used to display code snippets, having 30 lines
    # of license is annyoing.
    awk -v filter=0 -e '{if ($0 ~ "This file is part of the Soletta") filter=1; if (filter==0) print; if ($0 ~ "SUCH DAMAGE") filter=0;}' < $f > $OUTPUT/$f

    # Create svg from fbp
    if $FBP_TO_DOT --fbp=$f --dot=$f_dot; then
        echo "     GEN   $f_svg"
        dot -Tsvg $f_dot > $f_svg
        rm $f_dot
        echo "     GEN   $f_svg"

        # Create jgp thumbnail
        min=`convert $f_svg -format "%[fx:min(w,h)]" info:`
        convert $f_svg -background black -gravity center -extent ${min}x${min} $f_thumb
        convert $f_thumb -thumbnail $THUMB_SIZE $f_thumb
    # It may fail if any module wasn't built
    else
        echo "Failed to convert $f"
        continue
    fi

done
