sample-$(FLOW_GROVE_BUTTON_SAMPLE) += grove-button
sample-grove-button-$(FLOW_GROVE_BUTTON_SAMPLE) := grove-button.fbp
sample-grove-button-$(FLOW_GROVE_BUTTON_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json
sample-grove-button-$(FLOW_GROVE_BUTTON_SAMPLE)-deps := \
	flow/gpio.mod

sample-$(FLOW_GROVE_BUZZER_SAMPLE) += grove-buzzer
sample-grove-buzzer-$(FLOW_GROVE_BUZZER_SAMPLE) := grove-buzzer.fbp
sample-grove-buzzer-$(FLOW_GROVE_BUZZER_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json
sample-grove-buzzer-$(FLOW_GROVE_BUZZER_SAMPLE)-deps := flow/piezo-speaker.mod

sample-$(FLOW_GROVE_LED_ACCUMULATOR_SAMPLE) += grove-led-accumulator
sample-grove-led-accumulator-$(FLOW_GROVE_LED_ACCUMULATOR_SAMPLE) := grove-led-accumulator.fbp
sample-grove-led-accumulator-$(FLOW_GROVE_LED_ACCUMULATOR_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json
sample-grove-led-accumulator-$(FLOW_GROVE_LED_ACCUMULATOR_SAMPLE)-deps := \
	flow/boolean.mod \
	flow/constant.mod \
	flow/converter.mod \
	flow/int.mod \
	flow/pwm.mod \
	flow/timer.mod

sample-$(FLOW_GROVE_RELAY_SAMPLE) += grove-relay
sample-grove-relay-$(FLOW_GROVE_RELAY_SAMPLE) := grove-relay.fbp
sample-grove-relay-$(FLOW_GROVE_RELAY_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json
sample-grove-relay-$(FLOW_GROVE_RELAY_SAMPLE)-deps := \
	flow/gpio.mod

sample-$(FLOW_GROVE_SOUND_SENSOR_SAMPLE) += grove-sound-sensor
sample-grove-sound-sensor-$(FLOW_GROVE_SOUND_SENSOR_SAMPLE) := grove-sound-sensor.fbp
sample-grove-sound-sensor-$(FLOW_GROVE_SOUND_SENSOR_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json
sample-grove-sound-sensor-$(FLOW_GROVE_SOUND_SENSOR_SAMPLE)-deps := \
	flow/aio.mod \
	flow/constant.mod \
	flow/gpio.mod \
	flow/int.mod
