sample-$(FLOW_GROVE_BUTTON_SAMPLE) += grove-button
sample-grove-button-$(FLOW_GROVE_BUTTON_SAMPLE) := grove-button.fbp
sample-grove-button-$(FLOW_GROVE_BUTTON_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_BUZZER_SAMPLE) += grove-buzzer
sample-grove-buzzer-$(FLOW_GROVE_BUZZER_SAMPLE) := grove-buzzer.fbp
sample-grove-buzzer-$(FLOW_GROVE_BUZZER_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_LED_ACCUMULATOR_SAMPLE) += grove-led-accumulator
sample-grove-led-accumulator-$(FLOW_GROVE_LED_ACCUMULATOR_SAMPLE) := grove-led-accumulator.fbp
sample-grove-led-accumulator-$(FLOW_GROVE_LED_ACCUMULATOR_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_RELAY_SAMPLE) += grove-relay
sample-grove-relay-$(FLOW_GROVE_RELAY_SAMPLE) := grove-relay.fbp
sample-grove-relay-$(FLOW_GROVE_RELAY_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_SOUND_SENSOR_SAMPLE) += grove-sound-sensor
sample-grove-sound-sensor-$(FLOW_GROVE_SOUND_SENSOR_SAMPLE) := grove-sound-sensor.fbp
sample-grove-sound-sensor-$(FLOW_GROVE_SOUND_SENSOR_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_LED_WAVE_GENERATOR_SAMPLE) += grove-led-wave-generator
sample-grove-led-wave-generator-$(FLOW_GROVE_LED_WAVE_GENERATOR_SAMPLE) := grove-led-wave-generator.fbp
sample-grove-led-wave-generator-$(FLOW_GROVE_LED_WAVE_GENERATOR_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_LIGHT_SENSOR_SAMPLE) += grove-light-sensor
sample-grove-light-sensor-$(FLOW_GROVE_LIGHT_SENSOR_SAMPLE) := grove-light-sensor.fbp
sample-grove-light-sensor-$(FLOW_GROVE_LIGHT_SENSOR_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_ROTARY_ANGLE_SENSOR_SAMPLE) += grove-rotary-angle-sensor
sample-grove-rotary-angle-sensor-$(FLOW_GROVE_ROTARY_ANGLE_SENSOR_SAMPLE) := grove-rotary-angle-sensor.fbp
sample-grove-rotary-angle-sensor-$(FLOW_GROVE_ROTARY_ANGLE_SENSOR_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json

sample-$(FLOW_GROVE_THERMOMETER_SAMPLE) += grove-thermometer
sample-grove-thermometer-$(FLOW_GROVE_THERMOMETER_SAMPLE) := grove-thermometer.fbp
sample-grove-thermometer-$(FLOW_GROVE_THERMOMETER_SAMPLE)-conffile := sol-flow-intel-galileo-rev-g.json
