sample-$(FLOW_IO_SAMPLE) += \
	io-pwm \
	io-servo-motor

sample-io-pwm-$(FLOW_IO_SAMPLE) := \
	pwm.fbp
sample-io-pwm-$(FLOW_IO_SAMPLE)-conffile := \
	sol-flow-intel-edison-rev-c.json

sample-io-servo-motor-$(FLOW_IO_SAMPLE) := \
	servo-motor.fbp
sample-io-servo-motor-$(FLOW_IO_SAMPLE)-conffile := \
	sol-flow-intel-edison-rev-c.json
