sample-$(FLOW_IO_SAMPLE) += \
	io-pwm \
	io-servo-motor

sample-io-pwm-$(FLOW_IO_SAMPLE) := \
	pwm.fbp
sample-io-pwm-$(FLOW_IO_SAMPLE)-deps := \
	flow/pwm.mod
sample-io-pwm-$(FLOW_IO_SAMPLE)-conffile := \
	pwm.json

sample-io-servo-motor-$(FLOW_IO_SAMPLE) := \
	servo-motor.fbp
sample-io-servo-motor-$(FLOW_IO_SAMPLE)-deps := \
	flow/servo-motor.mod
sample-io-servo-motor-$(FLOW_IO_SAMPLE)-conffile := \
	servo-motor.json
