sample-$(FLOW_IO_SAMPLE) += \
	io-pwm \
	io-servo-motor

sample-io-pwm-$(FLOW_IO_SAMPLE) := \
	pwm.fbp
sample-io-pwm-$(FLOW_IO_SAMPLE)-deps := \
	flow/boolean.mod \
	flow/console.mod \
	flow/int.mod \
	flow/pwm.mod \
	flow/timer.mod
sample-io-pwm-$(FLOW_IO_SAMPLE)-conffile := \
	pwm.json

sample-io-servo-motor-$(FLOW_IO_SAMPLE) := \
	servo-motor.fbp
sample-io-servo-motor-$(FLOW_IO_SAMPLE)-deps := \
	flow/console.mod \
	flow/converter.mod \
	flow/int.mod \
	flow/servo-motor.mod \
	flow/timer.mod
sample-io-servo-motor-$(FLOW_IO_SAMPLE)-conffile := \
	servo-motor.json
