obj-$(FLOW_NODE_TYPE_UNIX_SOCKET) += unix-socket.mod
obj-unix-socket-$(FLOW_NODE_TYPE_UNIX_SOCKET) := unix-socket.json unix-socket.o
obj-unix-socket-$(FLOW_NODE_TYPE_UNIX_SOCKET) += unix-socket-impl.o
obj-unix-socket-$(FLOW_NODE_TYPE_UNIX_SOCKET)-type := flow
