sample-$(FLOW_MISC_FILE_COPY_SAMPLE) += file-copy
sample-file-copy-$(FLOW_MISC_FILE_COPY_SAMPLE) := file-copy.fbp

sample-$(FLOW_MISC_FS_PERSISTENCE_SAMPLE) += fs-persistence
sample-fs-persistence-$(FLOW_MISC_FS_PERSISTENCE_SAMPLE) := fs-persitence.fbp

sample-$(FLOW_MISC_RANDOM_NUMBERS_SAMPLE) += random-numbers
sample-random-numbers-$(FLOW_MISC_RANDOM_NUMBERS_SAMPLE) := random-numbers.fbp

sample-$(FLOW_MISC_TICKETS_QUEUE_SAMPLE) += tickets-queue
sample-tickets-queue-$(FLOW_MISC_TICKETS_QUEUE_SAMPLE) := tickets_queue.fbp

sample-$(FLOW_MISC_CHANGE_HOSTNAME_SAMPLE) += change_hostname
sample-tickets-queue-$(FLOW_MISC_CHANGE_HOSTNAME_SAMPLE) := change_hostname.fbp

sample-$(FLOW_MISC_CHANGE_TIMEZONE_SAMPLE) += change_timezone
sample-tickets-queue-$(FLOW_MISC_CHANGE_TIMEZONE_SAMPLE) := change_timezone.fbp

sample-$(FLOW_MISC_CHANGE_SYSTEM_CLOCK_SAMPLE) += change_system_clock
sample-tickets-queue-$(FLOW_MISC_CHANGE_SYSTEM_CLOCK_SAMPLE) := change_system_clock.fbp

sample-$(FLOW_MISC_CHANGE_LOCALE_SAMPLE) += change_locale
sample-tickets-queue-$(FLOW_MISC_CHANGE_LOCALE_SAMPLE) := change_locale.fbp
