sample-$(FLOW_MISC_FILE_COPY_SAMPLE) += file-copy
sample-file-copy-$(FLOW_MISC_FILE_COPY_SAMPLE) := file-copy.fbp
sample-file-copy-$(FLOW_MISC_FILE_COPY_SAMPLE)-deps := flow/file.mod

sample-$(FLOW_MISC_FS_PERSISTENCE_SAMPLE) += fs-persistence
sample-fs-persistence-$(FLOW_MISC_FS_PERSISTENCE_SAMPLE) := fs-persitence.fbp
sample-fs-persistence-$(FLOW_MISC_FS_PERSISTENCE_SAMPLE)-deps := flow/fs.mod

sample-$(FLOW_MISC_RANDOM_NUMBERS_SAMPLE) += random-numbers
sample-random-numbers-$(FLOW_MISC_RANDOM_NUMBERS_SAMPLE) := random-numbers.fbp

sample-$(FLOW_MISC_TICKETS_QUEUE_SAMPLE) += tickets-queue
sample-tickets-queue-$(FLOW_MISC_TICKETS_QUEUE_SAMPLE) := tickets_queue.fbp
sample-tickets-queue-$(FLOW_MISC_TICKETS_QUEUE_SAMPLE)-deps := flow/keyboard.mod
