sample-$(FLOW_HTTP_SERVER_SAMPLE) += \
	boolean \
	drange \
	irange \
	string \
	custom-ports \
	all \
	fbp-static-files

sample-boolean-$(FLOW_HTTP_SERVER_SAMPLE) := \
	boolean.fbp

sample-drange-$(FLOW_HTTP_SERVER_SAMPLE) := \
	drange.fbp

sample-irange-$(FLOW_HTTP_SERVER_SAMPLE) := \
	irange.fbp

sample-string-$(FLOW_HTTP_SERVER_SAMPLE) := \
	string.fbp

sample-custom-ports-$(FLOW_HTTP_SERVER_SAMPLE) := \
	custom-ports.fbp

sample-all-$(FLOW_HTTP_SERVER_SAMPLE) := \
	all.fbp

sample-fbp-static-files-$(FLOW_HTTP_SERVER_SAMPLE) := \
	static-files.fbp
