sample-$(FLOW_HTTP_SERVER_SAMPLE) += \
	boolean \
	drange \
	irange \
	string

sample-boolean-$(FLOW_HTTP_SERVER_SAMPLE) := \
	boolean.fbp
sample-boolean-$(FLOW_HTTP_SERVER_SAMPLE)-deps := \
	flow/http-server.mod \
	flow/keyboard.mod

sample-drange-$(FLOW_HTTP_SERVER_SAMPLE) := \
	drange.fbp
sample-drange-$(FLOW_HTTP_SERVER_SAMPLE)-deps := \
	flow/http-server.mod

sample-irange-$(FLOW_HTTP_SERVER_SAMPLE) := \
	irange.fbp
sample-irange-$(FLOW_HTTP_SERVER_SAMPLE)-deps := \
	flow/http-server.mod

sample-string-$(FLOW_HTTP_SERVER_SAMPLE) := \
	string.fbp
sample-string-$(FLOW_HTTP_SERVER_SAMPLE)-deps := \
	flow/http-server.mod
