sample-$(FLOW_HTTP_SERVER_SAMPLE) += \
	boolean \
	drange \
	irange \
	string

sample-boolean-$(FLOW_HTTP_SERVER_SAMPLE) := \
	boolean.fbp

sample-drange-$(FLOW_HTTP_SERVER_SAMPLE) := \
	drange.fbp

sample-irange-$(FLOW_HTTP_SERVER_SAMPLE) := \
	irange.fbp

sample-string-$(FLOW_HTTP_SERVER_SAMPLE) := \
	string.fbp
