obj-$(FLOW_NODE_TYPE_OIC) += oic.mod
obj-oic-$(FLOW_NODE_TYPE_OIC) := oic.json oic.o
obj-oic-$(FLOW_NODE_TYPE_OIC)-oic := y
obj-oic-$(FLOW_NODE_TYPE_OIC)-oic-dirs := $(OIC_DATA_MODELS)
obj-oic-$(FLOW_NODE_TYPE_OIC)-type := flow
